var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,q=!1,na,la=a=>a.startsWith("file://"),oa,r,t,pa,qa,v,w,x,y,ra;
function sa(){var a=oa.buffer;r=new Int8Array(a);pa=new Int16Array(a);t=new Uint8Array(a);qa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var z=0,A=null;function ta(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function xa(a){var b=ua;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(h)},Aa=[],Ba=[],Ca=()=>{var a=h.preRun.shift();Ba.push(a)},Da=!0,Ea="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ea)return Ea.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,
c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Fa=0,C={},Ga=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ha=a=>{na=a;Da||0<Fa||(h.onExit?.(a),q=!0);fa(a,new ya(a))},Ia=a=>{na=a;Ha(a)},Ja=()=>{if(!(Da||0<Fa))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},Ka=a=>{if(!q)try{a(),Ja()}catch(b){Ga(b)}},D=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;
d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;g++}}d[b]=0;return b-e},Ta=(a,b)=>{La=a;Ma=b;if(Na)if(Oa||=!0,0==a)G=function(){setTimeout(Pa,Math.max(0,Qa+b-performance.now())|0)};else if(1==a)G=function(){Ra(Pa)};else if(2==a){if("undefined"==typeof Sa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===
d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sa=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Sa=setImmediate;G=function(){Sa(Pa)}}},bb=(a,b,c,d,e)=>{function g(){return f<Ua?(Ja(),!1):!0}Na=a;Va=d;var f=Ua;Oa=!1;Pa=function(){if(!q)if(0<Wa.length){var l=Wa.shift();l.Cd(l.rd);if(Xa){var n=Xa,p=0==n%1?n-1:Math.floor(n);Xa=l.td?p:(8*n+(p+.5))/
9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Xa??0,p=Ya.yd??0,n?n<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(Pa,0)}else if(g())if(Za=Za+1|0,1==La&&1<Ma&&0!=Za%Ma)G();else{0==La&&(Qa=performance.now());a:if(!q){for(l of $a)if(!1===l())break a;Ka(a);for(n of ab)n()}g()&&G()}};e||(0<b?Ta(0,1E3/b):Ta(1,1),G());if(c)throw"unwind";},Oa=!1,G=null,Ua=0,Na=null,Va=0,La=0,Ma=0,Za=0,Wa=[],$a=[],ab=[];function cb(){G=null;Ua++}
var db=0;function Ra(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===db)db=b+1E3/60;else for(;b+2>=db;)db+=1E3/60;setTimeout(a,Math.max(db-b,0))}}
var Ya={},Qa,Pa,Sa,Xa,eb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],H=a=>{a=2<a?a?B(t,a):"":a;return eb[a]||("undefined"!=typeof document?document.querySelector(a):null)},fb=a=>0>eb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},gb=[],hb,I=a=>{var b=gb[a];b||(gb[a]=b=hb.get(a));return b};function ib(a){var b=J.wc[a];b.target.removeEventListener(b.vc,b.Xc,b.xc);J.wc.splice(a,1)}
function jb(){if(navigator.userActivation?navigator.userActivation.isActive:J.Kc&&J.md.Ic){var a=J.Bc;J.Bc=[];for(var b of a)b.Nc(...b.Tc)}}function K(a){if(!a.target)return-4;if(a.yc)a.Xc=function(c){++J.Kc;J.md=a;jb();a.zc(c);jb();--J.Kc},a.target.addEventListener(a.vc,a.Xc,a.xc),J.wc.push(a);else for(var b=0;b<J.wc.length;++b)J.wc[b].target==a.target&&J.wc[b].vc==a.vc&&ib(b--);return 0}function kb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={sd:0,Dd:0,Lc:0,Hc:0,Rc:0,Pc:0,Jc:0,wd:0,Id:0,vd:0,Bd:0,Mc:0,Rd:0,Oc:0,Fd(a,b,c){r.set(r.subarray(b,b+c),a)},Kd(){for(;J.wc.length;)ib(J.wc.length-1);J.Bc=[]},Kc:0,Bc:[],ud(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of J.Bc)if(e.Nc==a&&d(e.Tc,c))return;J.Bc.push({Nc:a,ad:b,Tc:c});J.Bc.sort((g,f)=>g.ad<f.ad)},Md(a){J.Bc=J.Bc.filter(b=>b.Nc!=a)},wc:[],Ld:(a,b)=>{for(var c=0;c<J.wc.length;++c)J.wc[c].target!=a||b&&b!=J.wc[c].vc||
ib(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},lb=(a,b,c,d,e,g)=>{J.Jc||(J.Jc=L(256));a={target:H(a),vc:g,yc:d,zc:(f=event)=>{var l=f.target.id?f.target.id:"",n=J.Jc;D(kb(f.target),n+0,128);D(l,n+128,128);I(d)(e,n,b)&&f.preventDefault()},xc:c};return K(a)},mb=(a,b,c,d,e,g)=>{J.Lc||(J.Lc=L(160));a={target:H(a),vc:g,yc:d,zc:f=>{var l=J.Lc;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=
f.metaKey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;D(f.key||"",l+32,32);D(f.code||"",l+64,32);D(f.char||"",l+96,32);D(f.locale||"",l+128,32);I(d)(e,l,b)&&f.preventDefault()},xc:c};return K(a)},nb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=fb(c);v[d+10]=b.clientX-
(a.left|0);v[d+11]=b.clientY-(a.top|0)},ob=(a,b,c,d,e,g)=>{J.Hc||(J.Hc=L(64));a=H(a);return K({target:a,Ic:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,vc:g,yc:d,zc:(f=event)=>{nb(J.Hc,f,a);I(d)(e,J.Hc,b)&&f.preventDefault()},xc:c})},pb=(a,b,c,d)=>{J.Mc||(J.Mc=L(257));return K({target:a,vc:"pointerlockchange",yc:d,zc:(e=event)=>{var g=J.Mc,f=document.pointerLockElement;r[g]=!!f;var l=f?.id||"";D(kb(f),g+1,128);D(l,g+129,128);I(d)(20,g,b)&&e.preventDefault()},xc:c})},qb=(a,b,c,d)=>K({target:a,
vc:"pointerlockerror",yc:d,zc:(e=event)=>{I(d)(38,0,b)&&e.preventDefault()},xc:c}),rb=(a,b,c,d)=>{J.Pc||(J.Pc=L(36));a=H(a);return K({target:a,vc:"resize",yc:d,zc:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=J.Pc;v[f>>2]=0;v[f+4>>2]=g.clientWidth;v[f+8>>2]=g.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;I(d)(10,f,b)&&e.preventDefault()}}},xc:c})},sb=(a,b,c,d,e,g)=>{J.Oc||(J.Oc=
L(1552));a=H(a);return K({target:a,Ic:"touchstart"==g||"touchend"==g,vc:g,yc:d,zc:f=>{var l={},n=f.touches;for(var p of n)p.Yc=p.$c=0,l[p.identifier]=p;for(var u of f.changedTouches)u.Yc=1,l[u.identifier]=u;for(var E of f.targetTouches)l[E.identifier].$c=1;n=J.Oc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;p=n+16;u=fb(a);E=0;for(let F of Object.values(l))if(l=p>>2,v[l]=F.identifier,v[l+1]=F.screenX,v[l+2]=F.screenY,v[l+3]=F.clientX,v[l+4]=F.clientY,
v[l+5]=F.pageX,v[l+6]=F.pageY,r[p+28]=F.Yc,r[p+29]=F.$c,v[l+8]=F.clientX-(u.left|0),v[l+9]=F.clientY-(u.top|0),p+=48,31<++E)break;v[n+8>>2]=E;I(d)(e,n,b)&&f.preventDefault()},xc:c})},M,tb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},ub=a=>{var b=a.getExtension("OES_vertex_array_object");
b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},vb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},wb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},xb=1,N=[],O=[],yb=[],zb=[],P=[],Q=[],Ab=[],Bb=[],R=[],Cb={},Db=4,Eb=0,Fb=a=>{for(var b=xb++,c=a.length;c<b;c++)a[c]=null;return b},T=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=M[c](),f=g&&Fb(d);g?(g.name=f,d[f]=g):S||=1282;v[b+4*e>>2]=f}},Hb=(a,b)=>{a.ld||(a.ld=a.getContext,a.getContext=function(d,e){e=a.ld(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Zc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Gb(c,b):0},Gb=(a,b)=>{var c=Fb(Bb),d={handle:c,attributes:b,version:b.Zc,Sc:a};a.canvas&&(a.canvas.qd=d);Bb[c]=d;("undefined"==typeof b.Wc||b.Wc)&&Ib(d);return c},Ib=a=>{a||=U;if(!a.pd){a.pd=!0;var b=a.Sc;b.Hd=b.getExtension("WEBGL_multi_draw");b.Ad=b.getExtension("EXT_polygon_offset_clamp");b.zd=b.getExtension("EXT_clip_control");b.Sd=b.getExtension("WEBGL_polygon_mode");tb(b);ub(b);vb(b);b.xd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Ed=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Vc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Vc)b.Vc=b.getExtension("EXT_disjoint_timer_query");wb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},S,U,Jb=(a,b,c,d,e,g)=>{a={target:H(a),vc:g,yc:d,zc:(f=event)=>{I(d)(e,0,b)&&f.preventDefault()},xc:c};K(a)},Kb=(a,b,c,d)=>{J.Rc||(J.Rc=L(96));return K({target:a,Ic:!0,vc:"wheel",yc:d,zc:(e=event)=>{var g=J.Rc;nb(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>3]=e.deltaY;y[g+80>>3]=e.deltaZ;
v[g+88>>2]=e.deltaMode;I(d)(9,g,b)&&e.preventDefault()},xc:c})},Lb=["default","low-power","high-performance"],Mb={},Ob=()=>{if(!Nb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Mb)void 0===Mb[b]?delete a[b]:a[b]=Mb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Nb=c}return Nb},Nb,Pb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=
d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Qb=[null,[],[]],Rb=[],Sb=()=>{var a=wb(M);return a=a.concat(a.map(b=>"GL_"+b))},Tb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=M.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>U.version){S||=1282;return}c=Sb().length;break;case 33307:case 33308:if(2>U.version){S||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=M.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":S||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:S||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){S||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:S||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else S||=1281},Ub=a=>{var b=Pb(a)+1,c=L(b);c&&D(a,c,b);return c},Vb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Wb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?w:qa},V=a=>{var b=M.nd;if(b){var c=b.Dc[a];"number"==typeof c&&(b.Dc[a]=c=M.getUniformLocation(b,b.jd[a]+(0<c?`[${c}]`:"")));return c}S||=1282},W=[],Xb=[],X=a=>{var b=Pb(a)+1,c=Yb(b);D(a,c,b);return c},ac=a=>{var b=["string","array","number"],c={string:n=>{var p=0;null!==n&&void 0!==n&&0!==n&&(p=X(n));return p},array:n=>{var p=Yb(n.length);r.set(n,p);return p}},d=h._util_emsc_loadfile,e=[],g=0;if(a)for(var f=0;f<a.length;f++){var l=c[b[f]];l?(0===g&&(g=Zb()),e[f]=l(a[f])):e[f]=a[f]}a=d(...e);return a=
function(n){0!==g&&$b(g);return n}(a)},bc=a=>{var b=Zb();a();$b(b)};h.requestAnimationFrame=Ra;h.pauseMainLoop=cb;h.resumeMainLoop=function(){Ua++;var a=La,b=Ma,c=Na;Na=null;bb(c,0,!1,Va,!0);Ta(a,b);G()};h.preMainLoop&&$a.push(h.preMainLoop);h.postMainLoop&&ab.push(h.postMainLoop);for(let a=0;32>a;++a)Rb.push(Array(a));for(var cc=new Float32Array(288),Y=0;288>=Y;++Y)W[Y]=cc.subarray(0,Y);var dc=new Int32Array(288);for(Y=0;288>=Y;++Y)Xb[Y]=dc.subarray(0,Y);h.noExitRuntime&&(Da=h.noExitRuntime);
h.print&&(ma=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(m=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);
function ec(){var a=document.getElementById("picker");const b=a.files[0];a.value=null;console.log("--- load file:");console.log("  name: "+b.name);console.log("  type: "+b.type);console.log("  size: "+b.size);256E3>b.size?(a=new FileReader,a.onload=c=>{console.log("file loaded!");(c=c.target.result)?(console.log("content length: "+c.byteLength),c=new Uint8Array(c),0==ac([b.name,c,c.length])&&console.warn("util_emsc_loadfile() failed!")):console.warn("load result empty!")},a.readAsArrayBuffer(b)):
console.warn("ignoring file because it is too big")}
var L,fc,gc,hc,ic,jc,kc,lc,mc,$b,Yb,Zb,nc={oa:function(){return 0},lb:function(){return 0},mb:function(){},pb:()=>ta(""),cb:()=>{Da=!1;Fa=0},db:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ka(()=>mc(a,performance.now()))},b);C[a]={id:c,Qd:b};return 0},eb:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();w[a>>2]=60*Math.max(g,e);v[b>>2]=Number(g!=e);b=f=>{var l=Math.abs(f);
return`UTC${0<=f?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(D(a,c,17),D(b,d,17)):(D(a,d,17),D(b,c,17))},fb:function(a,b,c){if(!(0<=a&&3>=a))return 28;ra[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},Wa:function(a,b,c){a=a?B(t,a):"";let d="";for(var e=0;e<c;e++)d+=String.fromCharCode(t[b+e]);console.log(btoa(d));b=document.createElement("a");b.setAttribute("href","data:application/octet-stream;base64,"+btoa(d));
b.setAttribute("download",a);b.style.display="none";document.body.appendChild(b);b.click();document.body.removeChild(b)},y:function(a,b){a=a?B(t,a):"";b=b?B(t,b):"";const c=document.createElement("a");c.setAttribute("href","data:text/plain;charset=utf-8,"+encodeURIComponent(b));c.setAttribute("download",a);c.style.display="none";document.body.appendChild(c);c.click();document.body.removeChild(c)},dc:function(){h.emsc_js_onload=ec},cc:function(){return navigator.userAgent.includes("Macintosh")?1:0},
Ua:function(){document.getElementById("picker").click()},Ka:function(a){if(void 0===window.localStorage)return 0;a=a?B(t,a):"";return(a=window.localStorage.getItem(a))?Ub(a):0},Ta:function(a){a=a?B(t,a):"";window.open(a)},Na:function(a,b){a=a?B(t,a):"";b=b?B(t,b):"";window.localStorage.setItem(a,b)},Ra:()=>{cb();Na=null},ia:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ka:(a,b,c)=>{a=H(a);if(!a)return-4;a=fb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Sa:()=>performance.now(),Ya:(a,
b)=>{function c(d){I(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},gb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);sa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},S:(a,b,c,d)=>lb(a,b,c,d,12,"blur"),ha:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},T:(a,b,c,d)=>
lb(a,b,c,d,13,"focus"),aa:(a,b,c,d)=>mb(a,b,c,d,2,"keydown"),_:(a,b,c,d)=>mb(a,b,c,d,1,"keypress"),$:(a,b,c,d)=>mb(a,b,c,d,3,"keyup"),Za:(a,b,c)=>{a=I(a);bb(a,b,c)},ga:(a,b,c,d)=>ob(a,b,c,d,5,"mousedown"),da:(a,b,c,d)=>ob(a,b,c,d,33,"mouseenter"),ca:(a,b,c,d)=>ob(a,b,c,d,34,"mouseleave"),ea:(a,b,c,d)=>ob(a,b,c,d,8,"mousemove"),fa:(a,b,c,d)=>ob(a,b,c,d,6,"mouseup"),V:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?pb(a,b,c,d):-4:-1,U:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?qb(a,
b,c,d):-4:-1,ja:(a,b,c,d)=>rb(a,b,c,d),W:(a,b,c,d)=>sb(a,b,c,d,25,"touchcancel"),X:(a,b,c,d)=>sb(a,b,c,d,23,"touchend"),Y:(a,b,c,d)=>sb(a,b,c,d,24,"touchmove"),Z:(a,b,c,d)=>sb(a,b,c,d,22,"touchstart"),R:(a,b,c,d)=>{Jb(a,b,c,d,31,"webglcontextlost");return 0},Q:(a,b,c,d)=>{Jb(a,b,c,d,32,"webglcontextrestored");return 0},ba:(a,b,c,d)=>(a=H(a))?"undefined"!=typeof a.onwheel?Kb(a,b,c,d):-1:-4,Xa:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+
4],preserveDrawingBuffer:!!r[b+5],powerPreference:Lb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Zc:v[c+4],Gd:v[c+5],Wc:r[b+24],od:r[b+25],Jd:v[c+7],Nd:r[b+32]};a=H(a);return!a||b.od?0:Hb(a,b)},Va:a=>{U=Bb[a];h.ctx=M=U?.Sc;return!a||M?0:-5},nb:(a,b)=>{var c=0,d=0,e;for(e of Ob()){var g=b+c;w[a+d>>2]=g;c+=D(e,g,Infinity)+1;d+=4}return 0},ob:(a,b)=>{var c=Ob();w[a>>2]=c.length;a=0;for(var d of c)a+=Pb(d)+1;w[b>>2]=a;return 0},na:()=>52,kb:()=>52,ib:function(){return 70},jb:(a,b,c,d)=>{for(var e=
0,g=0;g<c;g++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=a,u=t[f+n],E=Qb[p];0===u||10===u?((1===p?ma:k)(B(E)),E.length=0):E.push(u)}e+=l}w[d>>2]=e;return 0},p:a=>M.activeTexture(a),B:(a,b)=>{M.attachShader(O[a],Q[b])},b:(a,b)=>{35051==a?M.Uc=b:35052==a&&(M.Cc=b);M.bindBuffer(a,N[b])},a:(a,b,c)=>{M.bindBufferBase(a,b,N[c])},Ib:(a,b,c,d,e)=>{M.bindBufferRange(a,b,N[c],d,e)},i:(a,b)=>{M.bindFramebuffer(a,yb[b])},Tb:(a,b)=>{M.bindRenderbuffer(a,zb[b])},o:(a,b)=>{M.bindSampler(a,R[b])},
d:(a,b)=>{M.bindTexture(a,P[b])},P:a=>{M.bindVertexArray(Ab[a])},K:(a,b,c,d)=>M.blendColor(a,b,c,d),L:(a,b)=>M.blendEquationSeparate(a,b),M:(a,b,c,d)=>M.blendFuncSeparate(a,b,c,d),sb:(a,b,c,d,e,g,f,l,n,p)=>M.blitFramebuffer(a,b,c,d,e,g,f,l,n,p),Ga:(a,b,c,d)=>{2<=U.version?c&&b?M.bufferData(a,t,d,c,b):M.bufferData(a,b,d):M.bufferData(a,c?t.subarray(c,c+b):b,d)},E:(a,b,c,d)=>{2<=U.version?c&&M.bufferSubData(a,b,t,d,c):M.bufferSubData(a,b,t.subarray(d,d+c))},Qb:a=>M.checkFramebufferStatus(a),Pb:(a,b,
c,d)=>M.clearBufferfi(a,b,c,d),ra:(a,b,c)=>{M.clearBufferfv(a,b,x,c>>2)},Ob:(a,b,c)=>{M.clearBufferiv(a,b,v,c>>2)},q:(a,b,c,d)=>{M.colorMask(!!a,!!b,!!c,!!d)},Yb:a=>{M.compileShader(Q[a])},Ba:(a,b,c,d,e,g,f,l,n)=>{2<=U.version?M.Cc||!l?M.compressedTexSubImage2D(a,b,c,d,e,g,f,l,n):M.compressedTexSubImage2D(a,b,c,d,e,g,f,t,n,l):M.compressedTexSubImage2D(a,b,c,d,e,g,f,t.subarray(n,n+l))},Aa:(a,b,c,d,e,g,f,l,n,p,u)=>{M.Cc?M.compressedTexSubImage3D(a,b,c,d,e,g,f,l,n,p,u):M.compressedTexSubImage3D(a,b,
c,d,e,g,f,l,n,t,u,p)},ya:()=>{var a=Fb(O),b=M.createProgram();b.name=a;b.Gc=b.Ec=b.Fc=0;b.Qc=1;O[a]=b;return a},_b:a=>{var b=Fb(Q);Q[b]=M.createShader(a);return b},H:a=>M.cullFace(a),Ja:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=N[d];e&&(M.deleteBuffer(e),e.name=0,N[d]=null,d==M.Uc&&(M.Uc=0),d==M.Cc&&(M.Cc=0))}},v:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=yb[d];e&&(M.deleteFramebuffer(e),e.name=0,yb[d]=null)}},m:a=>{if(a){var b=O[a];b?(M.deleteProgram(b),b.name=0,O[a]=null):S||=1281}},
F:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=zb[d];e&&(M.deleteRenderbuffer(e),e.name=0,zb[d]=null)}},n:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=R[d];e&&(M.deleteSampler(e),e.name=0,R[d]=null)}},r:a=>{if(a){var b=Q[a];b?(M.deleteShader(b),Q[a]=null):S||=1281}},j:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=P[d];e&&(M.deleteTexture(e),e.name=0,P[d]=null)}},Ia:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];M.deleteVertexArray(Ab[d]);Ab[d]=null}},x:a=>M.depthFunc(a),w:a=>{M.depthMask(!!a)},
e:a=>M.disable(a),N:a=>{M.disableVertexAttribArray(a)},ub:(a,b,c)=>{M.drawArrays(a,b,c)},vb:(a,b,c,d)=>{M.drawArraysInstanced(a,b,c,d)},ta:(a,b)=>{for(var c=Rb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];M.drawBuffers(c)},wb:(a,b,c,d)=>{M.drawElements(a,b,c,d)},xb:(a,b,c,d,e)=>{M.drawElementsInstanced(a,b,c,d,e)},h:a=>M.enable(a),Jb:a=>{M.enableVertexAttribArray(a)},sa:(a,b,c,d)=>{M.framebufferRenderbuffer(a,b,c,zb[d])},k:(a,b,c,d,e)=>{M.framebufferTexture2D(a,b,c,P[d],e)},A:(a,b,c,d,e)=>{M.framebufferTextureLayer(a,
b,P[c],d,e)},I:a=>M.frontFace(a),Ha:(a,b)=>{T(a,b,"createBuffer",N)},O:(a,b)=>{T(a,b,"createFramebuffer",yb)},Ub:(a,b)=>{T(a,b,"createRenderbuffer",zb)},za:(a,b)=>{T(a,b,"createSampler",R)},Fa:(a,b)=>{T(a,b,"createTexture",P)},Qa:(a,b)=>{T(a,b,"createVertexArray",Ab)},Vb:(a,b)=>M.getAttribLocation(O[a],b?B(t,b):""),c:(a,b)=>Tb(a,b),ac:(a,b,c,d)=>{a=M.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,d,b):0;c&&(v[c>>2]=b)},wa:(a,b,c)=>{if(c)if(a>=xb)S||=1281;else if(a=O[a],35716==
b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Gc){var d=M.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Gc=Math.max(a.Gc,M.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Gc}else if(35722==b){if(!a.Ec)for(d=M.getProgramParameter(a,35721),b=0;b<d;++b)a.Ec=Math.max(a.Ec,M.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.Ec}else if(35381==b){if(!a.Fc)for(d=M.getProgramParameter(a,35382),b=0;b<d;++b)a.Fc=Math.max(a.Fc,M.getActiveUniformBlockName(a,
b).length+1);v[c>>2]=a.Fc}else v[c>>2]=M.getProgramParameter(a,b);else S||=1281},Wb:(a,b,c,d)=>{a=M.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,d,b):0;c&&(v[c>>2]=b)},ua:(a,b,c)=>{c?35716==b?(a=M.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=M.getShaderSource(Q[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=M.getShaderParameter(Q[a],b):S||=1281},Oa:(a,b)=>{if(2>U.version)return S||=1282,0;var c=Cb[a];if(c)return 0>b||b>=c.length?(S||=1281,
0):c[b];switch(a){case 7939:return c=Sb().map(Ub),c=Cb[a]=c,0>b||b>=c.length?(S||=1281,0):c[b];default:return S||=1280,0}},va:(a,b)=>{b=b?B(t,b):"";if(a=O[a]){var c=a,d=c.Dc,e=c.kd,g;if(!d){c.Dc=d={};c.jd={};var f=M.getProgramParameter(c,35718);for(g=0;g<f;++g){var l=M.getActiveUniform(c,g);var n=l.name;l=l.size;var p=Vb(n);p=0<p?n.slice(0,p):n;var u=c.Qc;c.Qc+=l;e[p]=[l,u];for(n=0;n<l;++n)d[u]=n,c.jd[u++]=p}}c=a.Dc;d=0;e=b;g=Vb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.kd[e])&&
d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else S||=1281;return-1},rb:(a,b,c)=>{for(var d=Rb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];M.invalidateFramebuffer(a,d)},xa:a=>{a=O[a];M.linkProgram(a);a.Dc=0;a.kd={}},Pa:(a,b)=>{3317==a?Db=b:3314==a&&(Eb=b);M.pixelStorei(a,b)},J:(a,b)=>M.polygonOffset(a,b),tb:a=>M.readBuffer(a),Sb:(a,b,c,d,e)=>M.renderbufferStorageMultisample(a,b,c,d,e),C:(a,b,c)=>{M.samplerParameterf(R[a],b,c)},g:(a,b,c)=>{M.samplerParameteri(R[a],b,c)},t:(a,b,c,d)=>M.scissor(a,
b,c,d),Zb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=w[c+4*g>>2])?B(t,f,d?w[d+4*g>>2]:void 0):"";e+=f}M.shaderSource(Q[a],e)},Ma:(a,b,c)=>M.stencilFunc(a,b,c),qa:(a,b,c,d)=>M.stencilFuncSeparate(a,b,c,d),s:a=>M.stencilMask(a),La:(a,b,c)=>M.stencilOp(a,b,c),pa:(a,b,c,d)=>M.stencilOpSeparate(a,b,c,d),Da:(a,b,c,d,e)=>M.texStorage2D(a,b,c,d,e),Ca:(a,b,c,d,e,g)=>M.texStorage3D(a,b,c,d,e,g),f:(a,b,c,d,e,g,f,l,n)=>{if(2<=U.version){if(M.Cc){M.texSubImage2D(a,b,c,d,e,g,f,l,n);return}if(n){var p=Wb(l);
M.texSubImage2D(a,b,c,d,e,g,f,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}if(n){p=Wb(l);var u=g*((Eb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*p.BYTES_PER_ELEMENT+Db-1&-Db);n=p.subarray(n>>>31-Math.clz32(p.BYTES_PER_ELEMENT),n+u>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else n=null;M.texSubImage2D(a,b,c,d,e,g,f,l,n)},D:(a,b,c,d,e,g,f,l,n,p,u)=>{if(M.Cc)M.texSubImage3D(a,b,c,d,e,g,f,l,n,p,u);else if(u){var E=Wb(p);M.texSubImage3D(a,b,c,d,e,g,f,l,n,p,E,u>>>31-
Math.clz32(E.BYTES_PER_ELEMENT))}else M.texSubImage3D(a,b,c,d,e,g,f,l,n,p,null)},Hb:(a,b,c)=>{if(2<=U.version)b&&M.uniform1fv(V(a),x,c>>2,b);else{if(288>=b)for(var d=W[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);M.uniform1fv(V(a),d)}},$b:(a,b)=>{M.uniform1i(V(a),b)},Db:(a,b,c)=>{if(2<=U.version)b&&M.uniform1iv(V(a),v,c>>2,b);else{if(288>=b)for(var d=Xb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);M.uniform1iv(V(a),d)}},Gb:(a,b,c)=>{if(2<=U.version)b&&M.uniform2fv(V(a),
x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=W[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);M.uniform2fv(V(a),d)}},Cb:(a,b,c)=>{if(2<=U.version)b&&M.uniform2iv(V(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Xb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);M.uniform2iv(V(a),d)}},Fb:(a,b,c)=>{if(2<=U.version)b&&M.uniform3fv(V(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=W[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+
(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);M.uniform3fv(V(a),d)}},Ab:(a,b,c)=>{if(2<=U.version)b&&M.uniform3iv(V(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Xb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);M.uniform3iv(V(a),d)}},Eb:(a,b,c)=>{if(2<=U.version)b&&M.uniform4fv(V(a),x,c>>2,4*b);else{if(72>=b){var d=W[4*b],e=x;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+
3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);M.uniform4fv(V(a),d)}},zb:(a,b,c)=>{if(2<=U.version)b&&M.uniform4iv(V(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Xb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);M.uniform4iv(V(a),d)}},yb:(a,b,c,d)=>{if(2<=U.version)b&&M.uniformMatrix4fv(V(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=W[16*b],g=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+
2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(V(a),!!c,e)}},l:a=>{a=O[a];M.useProgram(a);M.nd=a},Kb:(a,b)=>{M.vertexAttribDivisor(a,b)},Lb:(a,b,c,d,e)=>{M.vertexAttribIPointer(a,b,c,d,e)},Nb:(a,b,c,d,e,g)=>{M.vertexAttribPointer(a,b,c,!!d,e,g)},u:(a,b,c,d)=>M.viewport(a,b,c,d),bb:Ha,Ea:function(){h.bd=
a=>{0!=gc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.bd)},Xb:function(){h.hd=a=>{const b=a.clipboardData.getData("text");bc(()=>{const c=X(b);fc(c)})};window.addEventListener("paste",h.hd)},Bb:function(){h.Od=[];h.cd=b=>{b.stopPropagation();b.preventDefault()};h.dd=b=>{b.stopPropagation();b.preventDefault()};h.ed=b=>{b.stopPropagation();b.preventDefault()};h.gd=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.Pd=c;hc(c.length);for(let e=
0;e<c.length;e++)bc(()=>{const g=X(c[e].name);ic(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);jc(b.clientX,b.clientY,d)};const a=h.Ac;a.addEventListener("dragenter",h.cd,!1);a.addEventListener("dragleave",h.dd,!1);a.addEventListener("dragover",h.ed,!1);a.addEventListener("drop",h.gd,!1)},ab:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},hb:function(a,b){0!==b&&(document.title=b?B(t,b):"");a=a?B(t,a):"";void 0!==
h.canvas&&("object"===typeof h.canvas?eb[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Ac=H(a);h.Ac||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Ac.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},bc:function(){window.removeEventListener("beforeunload",h.bd)},Rb:function(){window.removeEventListener("paste",h.hd)},qb:function(){const a=h.Ac;a.removeEventListener("dragenter",h.cd);a.removeEventListener("dragleave",
h.dd);a.removeEventListener("dragover",h.ed);a.removeEventListener("drop",h.gd)},z:function(){h.Ac&&h.Ac.requestPointerLock&&h.Ac.requestPointerLock()},ma:function(a,b){if(h.Ac){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;
default:a="auto"}h.Ac.style.cursor=a}},$a:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(t.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Mb:function(a){a=a?B(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");
b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},_a:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];bc(()=>{const e=X(c),g=X(d);lc(e,g)})}},G:function(){return navigator.userAgent.includes("Macintosh")?
1:0},la:function(a,b){b=b?B(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.ec;sa();hb=Z.qc;c=Z;h._util_emsc_loadfile=c.gc;L=c.hc;h.__sapp_emsc_onpaste=fc=c.ic;h.__sapp_html5_get_ask_leave_site=gc=c.jc;h.__sapp_emsc_begin_drop=hc=c.kc;h.__sapp_emsc_drop=ic=c.lc;h.__sapp_emsc_end_drop=jc=c.mc;h.__sapp_emsc_invoke_fetch_cb=c.nc;h._main=kc=c.oc;h.__sargs_add_kvp=lc=c.pc;mc=c.rc;$b=c.sc;Yb=c.tc;Zb=c.uc;z--;h.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;h.monitorRunDependencies?.(z);var b={a:nc};if(h.instantiateWasm)return new Promise(c=>
{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=h.locateFile?h.locateFile("vz80r.wasm",ia):ia+"vz80r.wasm";return a((await xa(b)).instance)})();function oc(a=[]){var b=kc;a.unshift(ea);var c=a.length,d=Yb(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=X(f);e+=4});w[e>>2]=0;try{var g=b(c,d);Ia(g)}catch(f){Ga(f)}}
function pc(a=da){function b(){h.calledRun=!0;if(!q){Z.fc();h.onRuntimeInitialized?.();h.noInitialRun||oc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Aa.push(c)}za(Aa)}}if(0<z)A=pc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ca();za(Ba);0<z?A=pc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();pc();
