var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,q=!1,na,la=a=>a.startsWith("file://"),r,t,oa,pa,v,w,x,y,qa;
function ra(){var a=sa.buffer;r=new Int8Array(a);oa=new Int16Array(a);t=new Uint8Array(a);pa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function ta(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ua&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function xa(a){var b=ua;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return wa(b,a)}class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=a=>{for(;0<a.length;)a.shift()(h)},Aa=[],Ba=[],Ca=()=>{var a=h.preRun.shift();Ba.push(a)},z=0,A=null,Da=!0,Ea=globalThis.TextDecoder&&new TextDecoder,B=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ea)return Ea.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,
c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Fa=0,C={},Ga=a=>{a instanceof ya||"unwind"==a||fa(1,a)},Ha=a=>{na=a;Da||0<Fa||(h.onExit?.(a),q=!0);fa(a,new ya(a))},Ia=()=>{if(!(Da||0<Fa))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},Ja=a=>{if(!q)try{a(),Ia()}catch(b){Ga(b)}},D=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>
6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;g++}}d[b]=0;return b-e},Ra=(a,b)=>{Ka=a;La=b;if(G)if(Ma||=!0,0==a)H=function(){setTimeout(Na,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)H=function(){Pa(Na)};else if(2==a){if(!Qa)if(globalThis.setImmediate)Qa=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===
d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}H=function(){Qa(Na)}}},$a=(a,b,c,d,e)=>{function g(){return f<Sa?(Ia(),!1):!0}G=a;Ta=d;var f=Sa;Ma=!1;Na=function(){if(!q)if(0<Ua.length){var l=Ua.shift();l.Ld(l.zd);if(Va){var n=Va,p=0==n%1?n-1:Math.floor(n);Va=l.Cd?p:(8*n+(p+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",
n=Va??0,p=Wa.Id??0,n?n<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(Na,0)}else if(g())if(Xa=Xa+1|0,1==Ka&&1<La&&0!=Xa%La)H();else{0==Ka&&(Oa=performance.now());a:if(!q){for(l of Ya)if(!1===l())break a;Ja(a);for(n of Za)n()}g()&&H()}};e||(0<b?Ra(0,1E3/b):Ra(1,1),H());if(c)throw"unwind";},Ma=!1,H=null,Sa=0,G=null,Ta=0,Ka=0,La=0,Xa=0,Ua=[],Ya=[],Za=[];function ab(){H=null;Sa++}var bb=0;
function Pa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===bb)bb=b+1E3/60;else for(;b+2>=bb;)bb+=1E3/60;setTimeout(a,Math.max(bb-b,0))}}var Wa={},Oa,Na,Qa,Va,cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],I=a=>{a=2<a?a?B(t,a):"":a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):null)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],J=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};
function gb(a){var b=K.Ac[a];b.target.removeEventListener(b.yc,b.dd,b.Cc);K.Ac.splice(a,1)}function hb(){if(navigator.userActivation?navigator.userActivation.isActive:K.Rc&&K.td.Oc){var a=K.Gc;K.Gc=[];for(var b of a)b.Uc(...b.$c)}}function L(a){if(!a.target)return-4;if(a.zc)a.dd=function(c){++K.Rc;K.td=a;hb();a.Ec(c);hb();--K.Rc},a.target.addEventListener(a.yc,a.dd,a.Cc),K.Ac.push(a);else for(var b=0;b<K.Ac.length;++b)K.Ac[b].target==a.target&&K.Ac[b].yc==a.yc&&gb(b--);return 0}
function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var K={Ad:0,Md:0,Sc:0,Mc:0,Yc:0,Wc:0,Pc:0,Gd:0,Qd:0,Fd:0,Qc:0,Tc:0,$d:0,Vc:0,Sd(){for(;K.Ac.length;)gb(K.Ac.length-1);K.Gc=[]},Rc:0,Gc:[],Ed(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of K.Gc)if(e.Uc==a&&d(e.$c,c))return;K.Gc.push({Uc:a,jd:b,$c:c});K.Gc.sort((g,f)=>g.jd<f.jd)},Ud(a){K.Gc=K.Gc.filter(b=>b.Uc!=a)},Ac:[],Td:(a,b)=>{for(var c=0;c<K.Ac.length;++c)K.Ac[c].target!=a||b&&b!=K.Ac[c].yc||gb(c--)},Vd(a){var b,c;for([b,c]of K.Ac.entries())if(c.target===
a.target&&c.Bc===a.Bc&&c.zc===a.zc&&c.Dc===a.Dc)return gb(b),0;return-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},jb=(a,b,c,d,e,g)=>{K.Pc||(K.Pc=M(256));a={target:I(a),yc:g,Bc:e,Dc:b,zc:d,Ec:(f=event)=>{var l=f.target.id?f.target.id:"",n=K.Pc;D(ib(f.target),n+0,128);D(l,n+128,128);J(d)(e,n,b)&&f.preventDefault()},Cc:c};return L(a)},kb=(a,b,c,d,e)=>{K.Qc||(K.Qc=M(276));return L({target:a,yc:e,Bc:19,Dc:b,zc:d,Ec:(g=event)=>{var f=K.Qc,l=document.fullscreenElement||
document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;r[f]=n;r[f+1]=K.fullscreenEnabled();var p=n?l:K.xd,u=p?.id||"";D(ib(p),f+2,128);D(u,f+130,128);v[f+260>>2]=p?p.clientWidth:0;v[f+264>>2]=p?p.clientHeight:0;v[f+268>>2]=screen.width;v[f+272>>2]=screen.height;n&&(K.xd=l);J(d)(19,f,b)&&g.preventDefault()},Cc:c})},lb=(a,b,c,d,e,g)=>{K.Sc||(K.Sc=M(160));a={target:I(a),yc:g,Bc:e,Dc:b,zc:d,Ec:f=>{var l=K.Sc;y[l>>3]=
f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;D(f.key||"",l+32,32);D(f.code||"",l+64,32);D(f.char||"",l+96,32);D(f.locale||"",l+128,32);J(d)(e,l,b)&&f.preventDefault()},Cc:c};return L(a)},mb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;
oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=db(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,e,g)=>{K.Mc||(K.Mc=M(64));a=I(a);return L({target:a,Oc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,yc:g,Bc:e,Dc:b,zc:d,Ec:(f=event)=>{mb(K.Mc,f,a);J(d)(e,K.Mc,b)&&f.preventDefault()},Cc:c})},ob=(a,b,c,d)=>{K.Tc||(K.Tc=M(257));return L({target:a,yc:"pointerlockchange",Bc:20,Dc:b,zc:d,Ec:(e=event)=>{var g=K.Tc,f=document.pointerLockElement;
r[g]=!!f;var l=f?.id||"";D(ib(f),g+1,128);D(l,g+129,128);J(d)(20,g,b)&&e.preventDefault()},Cc:c})},pb=(a,b,c,d)=>L({target:a,yc:"pointerlockerror",Bc:38,Dc:b,zc:d,Ec:(e=event)=>{J(d)(38,0,b)&&e.preventDefault()},Cc:c}),qb=(a,b,c,d)=>{K.Wc||(K.Wc=M(36));a=I(a);return L({target:a,yc:"resize",Bc:10,Dc:b,zc:d,Ec:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=K.Wc;v[f>>2]=0;v[f+4>>2]=g.clientWidth;v[f+8>>2]=g.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;
v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;J(d)(10,f,b)&&e.preventDefault()}}},Cc:c})},rb=(a,b,c,d,e,g)=>{K.Vc||(K.Vc=M(1552));a=I(a);return L({target:a,Oc:"touchstart"==g||"touchend"==g,yc:g,Bc:e,Dc:b,zc:d,Ec:f=>{var l={},n=f.touches;for(var p of n)p.ed=p.hd=0,l[p.identifier]=p;for(var u of f.changedTouches)u.ed=1,l[u.identifier]=u;for(var E of f.targetTouches)l[E.identifier].hd=1;n=K.Vc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=
f.metaKey;p=n+16;u=db(a);E=0;for(let F of Object.values(l))if(l=p>>2,v[l]=F.identifier,v[l+1]=F.screenX,v[l+2]=F.screenY,v[l+3]=F.clientX,v[l+4]=F.clientY,v[l+5]=F.pageX,v[l+6]=F.pageY,r[p+28]=F.ed,r[p+29]=F.hd,v[l+8]=F.clientX-(u.left|0),v[l+9]=F.clientY-(u.top|0),p+=48,31<++E)break;v[n+8>>2]=E;J(d)(e,n,b)&&f.preventDefault()},Cc:c})},N,sb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,
d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},tb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},ub=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},vb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},wb=1,O=[],P=[],xb=[],yb=[],Q=[],R=[],zb=[],Ab=[],S=[],Bb={},Cb=4,Db=0,Eb=a=>{for(var b=wb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=N[c](),f=g&&Eb(d);g?(g.name=f,d[f]=g):T||=1282;v[b+4*e>>2]=f}},Gb=(a,b)=>{a.sd||(a.sd=a.getContext,a.getContext=function(d,e){e=a.sd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.gd?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Fb(c,b):0},Fb=(a,b)=>{var c=Eb(Ab),d={handle:c,attributes:b,version:b.gd,Zc:a};a.canvas&&(a.canvas.yd=d);Ab[c]=d;if("undefined"==typeof b.cd||b.cd)if((a=d)||(a=V),!a.wd){a.wd=!0;b=a.Zc;b.Pd=b.getExtension("WEBGL_multi_draw");b.Kd=b.getExtension("EXT_polygon_offset_clamp");b.Jd=b.getExtension("EXT_clip_control");b.ae=b.getExtension("WEBGL_polygon_mode");sb(b);tb(b);ub(b);b.Hd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Nd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.bd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.bd)b.bd=b.getExtension("EXT_disjoint_timer_query");for(var e of vb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},T,V,Hb=(a,b,c,d,e,g)=>{a={target:I(a),yc:g,Bc:e,Dc:b,zc:d,Ec:(f=event)=>{J(d)(e,0,b)&&f.preventDefault()},Cc:c};L(a)},Ib=(a,b,c,d)=>{K.Yc||(K.Yc=M(96));return L({target:a,Oc:!0,yc:"wheel",Bc:9,Dc:b,zc:d,Ec:(e=event)=>{var g=K.Yc;mb(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>
3]=e.deltaY;y[g+80>>3]=e.deltaZ;v[g+88>>2]=e.deltaMode;J(d)(9,g,b)&&e.preventDefault()},Cc:c})},Jb=["default","low-power","high-performance"],Kb={},Mb=()=>{if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Lb=c}return Lb},Lb,Nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=
a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ob=[null,[],[]],Pb=[],Qb=()=>{var a=vb(N);return a=a.concat(a.map(b=>"GL_"+b))},Rb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Qb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=N.getParameter(a),
typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+
4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T||=1281},Sb=a=>{var b=Nb(a)+1,c=M(b);c&&D(a,c,b);return c},Tb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ub=a=>{a-=5120;return 0==a?r:1==a?t:2==a?oa:4==a?v:6==a?x:5==a||28922==a||
28520==a||30779==a||30782==a?w:pa},W=a=>{var b=N.ud;if(b){var c=b.Ic[a];"number"==typeof c&&(b.Ic[a]=c=N.getUniformLocation(b,b.qd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Vb=[],Y=a=>{var b=Nb(a)+1,c=Wb(b);D(a,c,b);return c},Zb=a=>{var b=["string","array","number"],c={string:n=>{var p=0;null!==n&&void 0!==n&&0!==n&&(p=Y(n));return p},array:n=>{var p=Wb(n.length);r.set(n,p);return p}},d=h._util_emsc_loadfile,e=[],g=0;if(a)for(var f=0;f<a.length;f++){var l=c[b[f]];l?(0===g&&(g=Xb()),e[f]=l(a[f])):
e[f]=a[f]}a=d(...e);return a=function(n){0!==g&&Yb(g);return n}(a)},$b=a=>{var b=Xb();a();Yb(b)};h.requestAnimationFrame=Pa;h.pauseMainLoop=ab;h.resumeMainLoop=function(){Sa++;var a=Ka,b=La,c=G;G=null;$a(c,0,!1,Ta,!0);Ra(a,b);H()};h.preMainLoop&&Ya.push(h.preMainLoop);h.postMainLoop&&Za.push(h.postMainLoop);for(let a=0;32>a;++a)Pb.push(Array(a));for(var ac=new Float32Array(288),Z=0;288>=Z;++Z)X[Z]=ac.subarray(0,Z);var bc=new Int32Array(288);for(Z=0;288>=Z;++Z)Vb[Z]=bc.subarray(0,Z);
h.noExitRuntime&&(Da=h.noExitRuntime);h.print&&(ma=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(m=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
function cc(){var a=document.getElementById("picker");const b=a.files[0];a.value=null;console.log("--- load file:");console.log("  name: "+b.name);console.log("  type: "+b.type);console.log("  size: "+b.size);256E3>b.size?(a=new FileReader,a.onload=c=>{console.log("file loaded!");(c=c.target.result)?(console.log("content length: "+c.byteLength),c=new Uint8Array(c),0==Zb([b.name,c,c.length])&&console.warn("util_emsc_loadfile() failed!")):console.warn("load result empty!")},a.readAsArrayBuffer(b)):
console.warn("ignoring file because it is too big")}
var M,dc,ec,fc,gc,hc,ic,jc,kc,Yb,Wb,Xb,sa,fb,lc={pa:function(){return 0},mb:function(){return 0},nb:function(){},qb:()=>ta(""),db:()=>{Da=!1;Fa=0},eb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ja(()=>kc(a,performance.now()))},b);C[a]={id:c,Zd:b};return 0},fb:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();w[a>>2]=60*Math.max(g,e);v[b>>2]=Number(g!=e);b=f=>{var l=Math.abs(f);
return`UTC${0<=f?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(D(a,c,17),D(b,d,17)):(D(a,d,17),D(b,c,17))},gb:function(a,b,c){if(!(0<=a&&3>=a))return 28;qa[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},Xa:function(a,b,c){a=a?B(t,a):"";let d="";for(var e=0;e<c;e++)d+=String.fromCharCode(t[b+e]);console.log(btoa(d));b=document.createElement("a");b.setAttribute("href","data:application/octet-stream;base64,"+btoa(d));
b.setAttribute("download",a);b.style.display="none";document.body.appendChild(b);b.click();document.body.removeChild(b)},z:function(a,b){a=a?B(t,a):"";b=b?B(t,b):"";const c=document.createElement("a");c.setAttribute("href","data:text/plain;charset=utf-8,"+encodeURIComponent(b));c.setAttribute("download",a);c.style.display="none";document.body.appendChild(c);c.click();document.body.removeChild(c)},fc:function(){h.emsc_js_onload=cc},ec:function(){return navigator.userAgent.includes("Macintosh")?1:0},
Ua:function(){document.getElementById("picker").click()},Ka:function(a){if(void 0===window.localStorage)return 0;a=a?B(t,a):"";return(a=window.localStorage.getItem(a))?Sb(a):0},Ta:function(a){a=a?B(t,a):"";window.open(a)},Na:function(a,b){a=a?B(t,a):"";b=b?B(t,b):"";window.localStorage.setItem(a,b)},Ra:()=>{ab();G=null},ka:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ma:(a,b,c)=>{a=I(a);if(!a)return-4;a=db(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Sa:()=>performance.now(),Ya:(a,
b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},hb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},U:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),ja:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},V:(a,b,c,d)=>
jb(a,b,c,d,13,"focus"),T:(a,b,c,d)=>{if(!K.fullscreenEnabled())return-1;a=I(a);if(!a)return-4;kb(a,b,c,d,"webkitfullscreenchange");return kb(a,b,c,d,"fullscreenchange")},ca:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),aa:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),ba:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),Za:(a,b,c)=>{a=J(a);$a(a,b,c)},ia:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),fa:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),ea:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),ga:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),ha:(a,b,c,d)=>nb(a,b,c,
d,6,"mouseup"),X:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?ob(a,b,c,d):-4:-1,W:(a,b,c,d)=>document.body?.requestPointerLock?(a=I(a))?pb(a,b,c,d):-4:-1,la:(a,b,c,d)=>qb(a,b,c,d),Y:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),Z:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),_:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),$:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),S:(a,b,c,d)=>{Hb(a,b,c,d,31,"webglcontextlost");return 0},R:(a,b,c,d)=>{Hb(a,b,c,d,32,"webglcontextrestored");return 0},da:(a,b,c,d)=>(a=I(a))?"undefined"!=
typeof a.onwheel?Ib(a,b,c,d):-1:-4,Wa:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Jb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],gd:v[c+4],Od:v[c+5],cd:r[b+24],vd:r[b+25],Rd:v[c+7],Wd:r[b+32]};a=I(a);return!a||b.vd?0:Gb(a,b)},Va:a=>{V=Ab[a];h.ctx=N=V?.Zc;return!a||N?0:-5},ob:(a,b)=>{var c=0,d=0,e;for(e of Mb()){var g=b+c;w[a+d>>2]=g;c+=D(e,g,Infinity)+1;d+=4}return 0},pb:(a,b)=>
{var c=Mb();w[a>>2]=c.length;a=0;for(var d of c)a+=Nb(d)+1;w[b>>2]=a;return 0},oa:()=>52,lb:()=>52,ib:function(){return 70},kb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=a,u=t[f+n],E=Ob[p];0===u||10===u?((1===p?ma:k)(B(E)),E.length=0):E.push(u)}e+=l}w[d>>2]=e;return 0},m:a=>N.activeTexture(a),D:(a,b)=>{N.attachShader(P[a],R[b])},a:(a,b)=>{35051==a?N.ad=b:35052==a&&(N.Hc=b);N.bindBuffer(a,O[b])},w:(a,b,c)=>{N.bindBufferBase(a,b,O[c])},Jb:(a,b,c,d,
e)=>{N.bindBufferRange(a,b,O[c],d,e)},h:(a,b)=>{N.bindFramebuffer(a,xb[b])},Ub:(a,b)=>{N.bindRenderbuffer(a,yb[b])},l:(a,b)=>{N.bindSampler(a,S[b])},c:(a,b)=>{N.bindTexture(a,Q[b])},Q:a=>{N.bindVertexArray(zb[a])},L:(a,b,c,d)=>N.blendColor(a,b,c,d),M:(a,b)=>N.blendEquationSeparate(a,b),N:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),sb:(a,b,c,d,e,g,f,l,n,p)=>N.blitFramebuffer(a,b,c,d,e,g,f,l,n,p),Ga:(a,b,c,d)=>{2<=V.version?c&&b?N.bufferData(a,t,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?t.subarray(c,
c+b):b,d)},E:(a,b,c,d)=>{2<=V.version?c&&N.bufferSubData(a,b,t,d,c):N.bufferSubData(a,b,t.subarray(d,d+c))},Rb:a=>N.checkFramebufferStatus(a),Qb:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),sa:(a,b,c)=>{N.clearBufferfv(a,b,x,c>>2)},Pb:(a,b,c)=>{N.clearBufferiv(a,b,v,c>>2)},n:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},Yb:a=>{N.compileShader(R[a])},u:(a,b,c,d,e,g,f,l,n)=>{2<=V.version?N.Hc||!l?N.compressedTexSubImage2D(a,b,c,d,e,g,f,l,n):N.compressedTexSubImage2D(a,b,c,d,e,g,f,t,n,l):N.compressedTexSubImage2D(a,
b,c,d,e,g,f,t.subarray(n,n+l))},Ba:(a,b,c,d,e,g,f,l,n,p,u)=>{N.Hc?N.compressedTexSubImage3D(a,b,c,d,e,g,f,l,n,p,u):N.compressedTexSubImage3D(a,b,c,d,e,g,f,l,n,t,u,p)},cc:()=>{var a=Eb(P),b=N.createProgram();b.name=a;b.Lc=b.Jc=b.Kc=0;b.Xc=1;P[a]=b;return a},$b:a=>{var b=Eb(R);R[b]=N.createShader(a);return b},I:a=>N.cullFace(a),Ja:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=O[d];e&&(N.deleteBuffer(e),e.name=0,O[d]=null,d==N.ad&&(N.ad=0),d==N.Hc&&(N.Hc=0))}},v:(a,b)=>{for(var c=0;c<a;++c){var d=
v[b+4*c>>2],e=xb[d];e&&(N.deleteFramebuffer(e),e.name=0,xb[d]=null)}},k:a=>{if(a){var b=P[a];b?(N.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},F:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=yb[d];e&&(N.deleteRenderbuffer(e),e.name=0,yb[d]=null)}},G:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(N.deleteSampler(e),e.name=0,S[d]=null)}},o:a=>{if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T||=1281}},i:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(N.deleteTexture(e),e.name=
0,Q[d]=null)}},Ia:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];N.deleteVertexArray(zb[d]);zb[d]=null}},y:a=>N.depthFunc(a),x:a=>{N.depthMask(!!a)},d:a=>N.disable(a),O:a=>{N.disableVertexAttribArray(a)},vb:(a,b,c)=>{N.drawArrays(a,b,c)},wb:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},ta:(a,b)=>{for(var c=Pb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];N.drawBuffers(c)},xb:(a,b,c,d)=>{N.drawElements(a,b,c,d)},yb:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},f:a=>N.enable(a),Kb:a=>{N.enableVertexAttribArray(a)},
s:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,yb[d])},g:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Q[d],e)},C:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,Q[c],d,e)},J:a=>N.frontFace(a),Ha:(a,b)=>{U(a,b,"createBuffer",O)},P:(a,b)=>{U(a,b,"createFramebuffer",xb)},Vb:(a,b)=>{U(a,b,"createRenderbuffer",yb)},za:(a,b)=>{U(a,b,"createSampler",S)},Ea:(a,b)=>{U(a,b,"createTexture",Q)},Qa:(a,b)=>{U(a,b,"createVertexArray",zb)},Wb:(a,b)=>N.getAttribLocation(P[a],b?B(t,b):""),b:(a,b)=>Rb(a,b),bc:(a,b,c,d)=>{a=
N.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,d,b):0;c&&(v[c>>2]=b)},wa:(a,b,c)=>{if(c)if(a>=wb)T||=1281;else if(a=P[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Lc){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Lc=Math.max(a.Lc,N.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Lc}else if(35722==b){if(!a.Jc)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.Jc=Math.max(a.Jc,N.getActiveAttrib(a,b).name.length+
1);v[c>>2]=a.Jc}else if(35381==b){if(!a.Kc)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.Kc=Math.max(a.Kc,N.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Kc}else v[c>>2]=N.getProgramParameter(a,b);else T||=1281},Xb:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,d,b):0;c&&(v[c>>2]=b)},ua:(a,b,c)=>{c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>
2]=N.getShaderParameter(R[a],b):T||=1281},Oa:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Bb[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Qb().map(Sb),c=Bb[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},va:(a,b)=>{b=b?B(t,b):"";if(a=P[a]){var c=a,d=c.Ic,e=c.rd,g;if(!d){c.Ic=d={};c.qd={};var f=N.getProgramParameter(c,35718);for(g=0;g<f;++g){var l=N.getActiveUniform(c,g);var n=l.name;l=l.size;var p=Tb(n);p=0<p?n.slice(0,p):n;var u=c.Xc;c.Xc+=
l;e[p]=[l,u];for(n=0;n<l;++n)d[u]=n,c.qd[u++]=p}}c=a.Ic;d=0;e=b;g=Tb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.rd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},rb:(a,b,c)=>{for(var d=Pb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];N.invalidateFramebuffer(a,d)},xa:a=>{a=P[a];N.linkProgram(a);a.Ic=0;a.rd={}},Pa:(a,b)=>{3317==a?Cb=b:3314==a&&(Db=b);N.pixelStorei(a,b)},K:(a,b)=>N.polygonOffset(a,b),ub:a=>N.readBuffer(a),Tb:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,
b,c,d,e),ya:(a,b,c)=>{N.samplerParameterf(S[a],b,c)},e:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},q:(a,b,c,d)=>N.scissor(a,b,c,d),Zb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=w[c+4*g>>2])?B(t,f,d?w[d+4*g>>2]:void 0):"";e+=f}N.shaderSource(R[a],e)},Ma:(a,b,c)=>N.stencilFunc(a,b,c),ra:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),p:a=>N.stencilMask(a),La:(a,b,c)=>N.stencilOp(a,b,c),qa:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),Da:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),Ca:(a,b,c,d,e,g)=>N.texStorage3D(a,
b,c,d,e,g),t:(a,b,c,d,e,g,f,l,n)=>{if(2<=V.version){if(N.Hc){N.texSubImage2D(a,b,c,d,e,g,f,l,n);return}if(n){var p=Ub(l);N.texSubImage2D(a,b,c,d,e,g,f,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}if(n){p=Ub(l);var u=g*((Db||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*p.BYTES_PER_ELEMENT+Cb-1&-Cb);n=p.subarray(n>>>31-Math.clz32(p.BYTES_PER_ELEMENT),n+u>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else n=null;N.texSubImage2D(a,b,c,d,e,g,f,l,n)},Aa:(a,b,c,d,e,g,f,l,
n,p,u)=>{if(N.Hc)N.texSubImage3D(a,b,c,d,e,g,f,l,n,p,u);else if(u){var E=Ub(p);N.texSubImage3D(a,b,c,d,e,g,f,l,n,p,E,u>>>31-Math.clz32(E.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,g,f,l,n,p,null)},Ib:(a,b,c)=>{if(2<=V.version)b&&N.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);N.uniform1fv(W(a),d)}},ac:(a,b)=>{N.uniform1i(W(a),b)},Db:(a,b,c)=>{if(2<=V.version)b&&N.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Vb[b],
e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);N.uniform1iv(W(a),d)}},Hb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(W(a),d)}},Cb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Vb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);N.uniform2iv(W(a),d)}},Gb:(a,
b,c)=>{if(2<=V.version)b&&N.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);N.uniform3fv(W(a),d)}},Bb:(a,b,c)=>{if(2<=V.version)b&&N.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Vb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);N.uniform3iv(W(a),d)}},Fb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4fv(W(a),
x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);N.uniform4fv(W(a),d)}},Ab:(a,b,c)=>{if(2<=V.version)b&&N.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Vb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);N.uniform4iv(W(a),d)}},zb:(a,b,c,d)=>{if(2<=V.version)b&&N.uniformMatrix4fv(W(a),
!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],g=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(W(a),!!c,e)}},j:a=>{a=P[a];N.useProgram(a);N.ud=a},Lb:(a,b)=>{N.vertexAttribDivisor(a,b)},Mb:(a,b,c,d,e)=>{N.vertexAttribIPointer(a,
b,c,d,e)},Nb:(a,b,c,d,e,g)=>{N.vertexAttribPointer(a,b,c,!!d,e,g)},r:(a,b,c,d)=>N.viewport(a,b,c,d),cb:Ha,Fa:function(){h.kd=a=>{0!=ec()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.kd)},_b:function(){h.pd=a=>{const b=a.clipboardData.getData("text");$b(()=>{const c=Y(b);dc(c)})};window.addEventListener("paste",h.pd)},Eb:function(){h.Xd=[];h.ld=b=>{b.stopPropagation();b.preventDefault()};h.md=b=>{b.stopPropagation();b.preventDefault()};h.nd=b=>{b.stopPropagation();
b.preventDefault()};h.od=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.Yd=c;fc(c.length);for(let e=0;e<c.length;e++)$b(()=>{const g=Y(c[e].name);gc(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);hc(b.clientX,b.clientY,d)};const a=h.Fc;a.addEventListener("dragenter",h.ld,!1);a.addEventListener("dragleave",h.md,!1);a.addEventListener("dragover",h.nd,!1);a.addEventListener("drop",h.od,!1)},ab:function(){const a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},bb:function(a){h.Nc&&(URL.revokeObjectURL(h.Nc[a].Bd),h.Nc[a]=null)},jb:function(a,b){0!==b&&(document.title=b?B(t,b):"");a=a?B(t,a):"";void 0!==h.canvas&&("object"===typeof h.canvas?cb[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Fc=I(a);h.Fc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Fc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},dc:function(){window.removeEventListener("beforeunload",
h.kd)},Sb:function(){window.removeEventListener("paste",h.pd)},tb:function(){const a=h.Fc;a.removeEventListener("dragenter",h.ld);a.removeEventListener("dragleave",h.md);a.removeEventListener("dragover",h.nd);a.removeEventListener("drop",h.od)},B:function(){h.Fc&&h.Fc.requestPointerLock&&h.Fc.requestPointerLock()},A:function(a,b,c){if(h.Fc){if(0===b)a="none";else if(0!=c)a=h.Nc[a].Dd;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Fc.style.cursor=a}},$a:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(t.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},Ob:function(a){a=a?B(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},_a:function(){const a=(new URLSearchParams(window.location.search)).entries();
for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];$b(()=>{const e=Y(c),g=Y(d);jc(e,g)})}},H:function(){return navigator.userAgent.includes("Macintosh")?1:0},na:function(a,b){b=b?B(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function mc(a=[]){var b=ic;a.unshift(ea);var c=a.length,d=Wb(4*(c+1)),e=d,g;for(g of a)w[e>>2]=Y(g),e+=4;w[e>>2]=0;try{var f=b(c,d);na=f;Ha(f)}catch(l){Ga(l)}}
function nc(a=da){function b(){h.calledRun=!0;if(!q){oc.hc();h.onRuntimeInitialized?.();h.noInitialRun||mc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Aa.push(c)}za(Aa)}}if(0<z)A=nc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ca();za(Ba);0<z?A=nc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var oc;
(async function(){function a(c){c=oc=c.exports;h._util_emsc_loadfile=c.ic;M=c.jc;dc=h.__sapp_emsc_onpaste=c.kc;ec=h.__sapp_html5_get_ask_leave_site=c.lc;fc=h.__sapp_emsc_begin_drop=c.mc;gc=h.__sapp_emsc_drop=c.nc;hc=h.__sapp_emsc_end_drop=c.oc;h.__sapp_emsc_invoke_fetch_cb=c.pc;h.__sapp_emsc_set_fullscreen_flag=c.qc;ic=h._main=c.rc;jc=h.__sargs_add_kvp=c.sc;kc=c.uc;Yb=c.vc;Wb=c.wc;Xb=c.xc;sa=c.gc;fb=c.tc;ra();z--;h.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return oc}z++;h.monitorRunDependencies?.(z);
var b={a:lc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=h.locateFile?h.locateFile("vz80r.wasm",ia):ia+"vz80r.wasm";return a((await xa(b)).instance)})();nc();
