var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);typeof module!="undefined"&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),l=console.error.bind(console),m=!1,na,la=a=>a.startsWith("file://");
function oa(){if(!p?.buffer?.resizable){var a=pa.buffer;p=new Int8Array(a);qa=new Int16Array(a);r=new Uint8Array(a);ra=new Uint16Array(a);u=new Int32Array(a);v=new Uint32Array(a);w=new Float32Array(a);x=new Float64Array(a);sa=new BigInt64Array(a)}}function ta(){var a=h.preRun;a&&(typeof a=="function"&&(a=[a]),ua.push(...a));for(a=ua;a.length>0;)a.shift()(h)}function va(){var a=h.postRun;a&&(typeof a=="function"&&(a=[a]),wa.push(...a));for(a=wa;a.length>0;)a.shift()(h)}
function xa(a){h.onAbort?.(a);a=`Aborted(${a})`;l(a);m=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya;async function za(a){try{var b=await ja(a);return new Uint8Array(b)}catch{}if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function Aa(a,b){try{var c=await za(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),xa(d)}}
async function Ba(a){var b=ya;if(!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return Aa(b,a)}class Ca{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var p,wa=[],ua=[],Da=!0,Ea=globalThis.TextDecoder&&new TextDecoder,y=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&Ea)return Ea.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=(e&240)==224?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
r,z=(a,b)=>a?y(r,a,b):"",Fa=0,Ga=[0,31,60,91,121,152,182,213,244,274,305,335],Ha=[0,31,59,90,120,151,181,212,243,273,304,334],u,A={},Ia=a=>{a instanceof Ca||a=="unwind"||fa(1,a)},Ja=a=>{na=a;Da||Fa>0||(h.onExit?.(a),m=!0);fa(a,new Ca(a))},Ka=()=>{if(!(Da||Fa>0))try{var a=na;na=a;Ja(a)}catch(b){Ia(b)}},La=a=>{if(!m)try{a()}catch(b){Ia(b)}finally{Ka()}},B=(a,b,c)=>{var d=r;if(!(c>0))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);if(f<=127){if(b>=c)break;d[b++]=f}else if(f<=
2047){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(f<=65535){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;g++}}d[b]=0;return b-e},v,sa,Ra=(a,b)=>{Ma=a;Na=b;if(C)if(a==0)D=function(){setTimeout(G,Math.max(0,Oa+b-performance.now())|0)};else if(a==1)D=function(){Pa(G)};else{if(!Qa)if(globalThis.scheduler)Qa=scheduler.postTask.bind(scheduler);else if(globalThis.setImmediate)Qa=
setImmediate;else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);Qa=d=>{c.push(d);ba?postMessage("setimmediate"):postMessage("setimmediate","*")}}D=function(){Qa(G)}}},$a=(a,b,c,d,e)=>{function g(){return f<Sa?(Ka(),!1):!0}C=a;Ta=d;var f=Sa;G=function(){if(!m)if(Ua.length>0){var k=Ua.shift();k.Nd(k.Bd);if(Va){var n=Va,q=n%1==0?n-1:Math.floor(n);Va=k.Ed?q:(8*n+(q+.5))/9}h.setStatus&&(k=h.statusMessage||"Please wait...",n=Va??0,q=Wa.Kd??0,n?n<
q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(k):h.setStatus(""));g()&&setTimeout(G,0)}else if(g())if(Xa=Xa+1|0,Ma==1&&Na>1&&Xa%Na!=0)D();else{Ma==0&&(Oa=performance.now());a:if(!m){for(k of Ya)if(k()===!1)break a;La(a);for(n of Za)n()}g()&&D()}};e||(b>0?Ra(0,1E3/b):Ra(1,1),D());if(c)throw"unwind";},C=null,D=null,Sa=0,Ta=0,Ma=0,Na=0,Xa=0,Ua=[],Ya=[],Za=[];function ab(){D&&(D=null,Sa++)}var bb=0;
function Pa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(bb)for(;b+2>=bb;)bb+=1E3/60;else bb=b+1E3/60;setTimeout(a,Math.max(bb-b,0))}}var Wa={},Oa,G,Qa,Va,cb=[0,globalThis.document??0,globalThis.window??0],H=a=>{a=a>2?a?y(r,a):"":a;return cb[a]||globalThis.document?.querySelector(a)},db=a=>cb.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},x,eb=[],I=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};
function gb(a){var b=J.Bc[a];b.target.removeEventListener(b.Ac,b.hd,b.Ec);J.Bc.splice(a,1)}function hb(){if(navigator.userActivation?navigator.userActivation.isActive:J.Tc&&J.vd.Qc){var a=J.Ic;J.Ic=[];for(var b of a)b.Wc(...b.cd)}}function K(a){if(!a.target)return-4;if(a.Cc)a.hd=function(c){++J.Tc;J.vd=a;hb();a.Gc(c);hb();--J.Tc},a.target.addEventListener(a.Ac,a.hd,a.Ec),J.Bc.push(a);else for(var b=0;b<J.Bc.length;++b)J.Bc[b].target==a.target&&J.Bc[b].Ac==a.Ac&&gb(b--);return 0}
function ib(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var J={Cd:0,Od:0,Uc:0,Oc:0,$c:0,Yc:0,Rc:0,Id:0,Sd:0,Hd:0,Sc:0,Vc:0,be:0,Xc:0,Ud(){for(;J.Bc.length;)gb(J.Bc.length-1);J.Ic=[]},Tc:0,Ic:[],Gd(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var k=0;k<g.length;k++)if(g[k]!=f[k])return!1;return!0}for(var e of J.Ic)if(e.Wc==a&&d(e.cd,c))return;J.Ic.push({Wc:a,md:b,cd:c});J.Ic.sort((g,f)=>g.md-f.md)},Wd(a){J.Ic=J.Ic.filter(b=>b.Wc!=a)},Bc:[],Vd:(a,b)=>{for(var c=0;c<J.Bc.length;++c)J.Bc[c].target!=a||b&&b!=J.Bc[c].Ac||gb(c--)},Xd(a){var b=!1;
for(let c=0;c<J.Bc.length;++c){let d=J.Bc[c];d.target===a.target&&d.Dc===a.Dc&&d.Cc===a.Cc&&d.Fc===a.Fc&&(gb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled??document.webkitFullscreenEnabled}},jb=(a,b,c,d,e,g)=>{J.Rc||(J.Rc=L(256));a={target:H(a),Ac:g,Dc:e,Fc:b,Cc:d,Gc:f=>{var k=f.target.id??"",n=J.Rc;B(ib(f.target),n+0,128);B(k,n+128,128);I(d)(e,n,b)&&f.preventDefault()},Ec:c};return K(a)},kb=(a,b,c,d,e)=>{J.Sc||(J.Sc=L(276));return K({target:a,Ac:e,Dc:19,Fc:b,Cc:d,
Gc:g=>{var f=J.Sc,k=document.fullscreenElement??document.webkitFullscreenElement,n=!!k;p[f]=n;p[f+1]=J.fullscreenEnabled();var q=n?k:J.zd,t=q?.id??"";B(ib(q),f+2,128);B(t,f+130,128);u[f+260>>2]=q?.clientWidth??0;u[f+264>>2]=q?.clientHeight??0;u[f+268>>2]=screen.width;u[f+272>>2]=screen.height;n&&(J.zd=k);I(d)(19,f,b)&&g.preventDefault()},Ec:c})},lb=(a,b,c,d,e,g)=>{J.Uc||(J.Uc=L(160));a={target:H(a),Ac:g,Dc:e,Fc:b,Cc:d,Gc:f=>{var k=J.Uc;x[k>>3]=f.timeStamp;var n=k>>2;u[n+2]=f.location;p[k+12]=f.ctrlKey;
p[k+13]=f.shiftKey;p[k+14]=f.altKey;p[k+15]=f.metaKey;p[k+16]=f.repeat;u[n+5]=f.charCode;u[n+6]=f.keyCode;u[n+7]=f.which;B(f.key??"",k+32,32);B(f.code??"",k+64,32);B(f.char??"",k+96,32);B(f.locale??"",k+128,32);I(d)(e,k,b)&&f.preventDefault()},Ec:c};return K(a)},qa,mb=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;p[a+24]=b.ctrlKey;p[a+25]=b.shiftKey;p[a+26]=b.altKey;p[a+27]=b.metaKey;qa[d*2+14]=b.button;qa[d*2+15]=b.buttons;u[d+8]=b.movementX;
u[d+9]=b.movementY;a=db(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,e,g)=>{J.Oc||(J.Oc=L(64));a=H(a);return K({target:a,Qc:g!="mousemove"&&g!="mouseenter"&&g!="mouseleave",Ac:g,Dc:e,Fc:b,Cc:d,Gc:f=>{mb(J.Oc,f,a);I(d)(e,J.Oc,b)&&f.preventDefault()},Ec:c})},ob=(a,b,c,d)=>{J.Vc||(J.Vc=L(257));return K({target:a,Ac:"pointerlockchange",Dc:20,Fc:b,Cc:d,Gc:e=>{var g=J.Vc,f=document.pointerLockElement;p[g]=!!f;var k=f?.id??"";B(ib(f),g+1,128);B(k,g+129,128);I(d)(20,g,b)&&e.preventDefault()},
Ec:c})},pb=(a,b,c,d)=>K({target:a,Ac:"pointerlockerror",Dc:38,Fc:b,Cc:d,Gc:e=>{I(d)(38,0,b)&&e.preventDefault()},Ec:c}),qb=(a,b,c,d)=>{J.Yc||(J.Yc=L(36));a=H(a);return K({target:a,Ac:"resize",Dc:10,Fc:b,Cc:d,Gc:e=>{if(e.target==a){var g=document.body;if(g){var f=J.Yc;u[f>>2]=0;u[f+4>>2]=g.clientWidth;u[f+8>>2]=g.clientHeight;u[f+12>>2]=innerWidth;u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;I(d)(10,f,b)&&e.preventDefault()}}},
Ec:c})},rb=(a,b,c,d,e,g)=>{J.Xc||(J.Xc=L(1552));a=H(a);return K({target:a,Qc:g=="touchstart"||g=="touchend",Ac:g,Dc:e,Fc:b,Cc:d,Gc:f=>{var k={},n=f.touches;for(var q of n)q.jd=q.ld=0,k[q.identifier]=q;for(var t of f.changedTouches)t.jd=1,k[t.identifier]=t;for(var E of f.targetTouches)k[E.identifier].ld=1;n=J.Xc;x[n>>3]=f.timeStamp;p[n+12]=f.ctrlKey;p[n+13]=f.shiftKey;p[n+14]=f.altKey;p[n+15]=f.metaKey;q=n+16;t=db(a);E=0;for(let F of Object.values(k))if(k=q>>2,u[k]=F.identifier,u[k+1]=F.screenX,u[k+
2]=F.screenY,u[k+3]=F.clientX,u[k+4]=F.clientY,u[k+5]=F.pageX,u[k+6]=F.pageY,p[q+28]=F.jd,p[q+29]=F.ld,u[k+8]=F.clientX-(t.left|0),u[k+9]=F.clientY-(t.top|0),q+=48,++E>31)break;u[n+8>>2]=E;I(d)(e,n,b)&&f.preventDefault()},Ec:c})},M,sb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},tb=
a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},ub=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},vb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},wb=1,N=[],O=[],xb=[],yb=[],P=[],Q=[],zb=[],Ab=[],R=[],Bb={},Cb=4,Db=0,Eb=a=>{for(var b=wb++,c=a.length;c<b;c++)a[c]=null;return b},T=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=M[c](),f=g&&Eb(d);g?(g.name=f,d[f]=g):S||=1282;u[b+e*4>>2]=f}},Gb=(a,b)=>{a.ad||(a.ad=a.getContext,a.getContext=function(d,e){e=a.ad(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=b.kd>1?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Fb(c,b):0},Fb=(a,b)=>{var c=Eb(Ab),d={handle:c,attributes:b,version:b.kd,bd:a};a.canvas&&(a.canvas.Ad=d);Ab[c]=d;if(typeof b.gd=="undefined"||b.gd)if((a=d)||(a=U),!a.yd){a.yd=!0;b=a.bd;b.Rd=b.getExtension("WEBGL_multi_draw");b.Md=b.getExtension("EXT_polygon_offset_clamp");b.Ld=b.getExtension("EXT_clip_control");b.ce=b.getExtension("WEBGL_polygon_mode");sb(b);tb(b);ub(b);b.Jd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Pd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
a.version>=2&&(b.ed=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(a.version<2||!b.ed)b.ed=b.getExtension("EXT_disjoint_timer_query");for(var e of vb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},S,U,Hb=(a,b,c,d,e,g)=>{a={target:H(a),Ac:g,Dc:e,Fc:b,Cc:d,Gc:f=>{I(d)(e,0,b)&&f.preventDefault()},Ec:c};K(a)},Ib=(a,b,c,d)=>{J.$c||(J.$c=L(96));return K({target:a,Qc:!0,Ac:"wheel",Dc:9,Fc:b,Cc:d,Gc:e=>{var g=J.$c;mb(g,e,a);x[g+64>>3]=e.deltaX;x[g+72>>3]=e.deltaY;x[g+
80>>3]=e.deltaZ;u[g+88>>2]=e.deltaMode;I(d)(9,g,b)&&e.preventDefault()},Ec:c})},Jb=["default","low-power","high-performance"],Kb={},Mb=()=>{if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea},b;for(b in Kb)Kb[b]===void 0?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Lb=c}return Lb},Lb,Nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=
2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},Ob=[null,[],[]],w,Pb=[],Qb=()=>{var a=vb(M);return a=a.concat(a.map(b=>"GL_"+b))},Rb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=M.getParameter(34467);c=d?d.length:0;break;case 33309:if(U.version<2){S||=1282;return}c=Qb().length;break;case 33307:case 33308:if(U.version<2){S||=1280;return}c=a==33307?3:0}if(c===void 0)switch(d=M.getParameter(a),typeof d){case "number":c=d;
break;case "boolean":c=d?1:0;break;case "string":S||=1280;return;case "object":if(d===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:S||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+a*4>>2]=d[a];return}try{c=
d.name|0}catch(e){S||=1280;l(`GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:S||=1280;l(`GL_INVALID_ENUM in glGet0v: Native code calling glGet0v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else S||=1281},Sb=a=>{var b=Nb(a)+1,c=L(b);c&&B(a,c,b);return c},Tb=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),ra,Ub=a=>{a-=5120;return a==0?p:a==1?r:a==2?qa:a==4?u:a==6?w:a==5||a==28922||a==28520||a==30779||a==30782?v:
ra},V=a=>{var b=M.wd;if(b){var c=b.Kc[a];typeof c=="number"&&(b.Kc[a]=c=M.getUniformLocation(b,b.td[a]+(c>0?`[${c}]`:"")));return c}S||=1282},W=[],Vb=[],X=a=>{var b=Nb(a)+1,c=Wb(b);B(a,c,b);return c},Zb=a=>{var b=["string","array","number"],c={string:n=>{var q=0;n!==null&&n!==void 0&&n!==0&&(q=X(n));return q},array:n=>{var q=Wb(n.length);p.set(n,q);return q}},d=h._util_emsc_loadfile,e=[],g=0;if(a)for(var f=0;f<a.length;f++){var k=c[b[f]];k?(g||=Xb(),e[f]=k(a[f])):e[f]=a[f]}a=d(...e);return a=function(n){g&&
Yb(g);return n}(a)},$b=a=>{var b=Xb();a();Yb(b)};h.requestAnimationFrame=Pa;h.pauseMainLoop=ab;h.resumeMainLoop=function(){Sa++;var a=Ma,b=Na,c=C;C=null;$a(c,0,!1,Ta,!0);Ra(a,b);D()};for(let a=0;a<32;++a)Pb.push(Array(a));for(var ac=new Float32Array(288),Y=0;Y<=288;++Y)W[Y]=ac.subarray(0,Y);var bc=new Int32Array(288);for(Y=0;Y<=288;++Y)Vb[Y]=bc.subarray(0,Y);h.noExitRuntime&&(Da=h.noExitRuntime);h.print&&(ma=h.print);h.printErr&&(l=h.printErr);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);
var Z=h.preInit;if(Z)for(typeof Z=="function"&&(h.preInit=Z=[Z]);Z.length>0;)Z.shift()();
function cc(){var a=document.getElementById("picker"),b=a.files[0];a.value=null;console.log("--- load file:");console.log("  name: "+b.name);console.log("  type: "+b.type);console.log("  size: "+b.size);b.size<256E3?(a=new FileReader,a.onload=c=>{console.log("file loaded!");(c=c.target.result)?(console.log("content length: "+c.byteLength),c=new Uint8Array(c),Zb([b.name,c,c.length])==0&&console.warn("util_emsc_loadfile() failed!")):console.warn("load result empty!")},a.readAsArrayBuffer(b)):console.warn("ignoring file because it is too big")}
var L,dc,ec,fc,hc,ic,jc,kc,lc,Yb,Wb,Xb,pa,fb,mc={sa:function(){return 0},rb:function(){return 0},sb:function(){},wb:()=>xa(""),lb:()=>{Da=!1;Fa=0},mb:function(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);if(isNaN(a.getTime()))return 1;u[b>>2]=a.getSeconds();u[b+4>>2]=a.getMinutes();u[b+8>>2]=a.getHours();u[b+12>>2]=a.getDate();u[b+16>>2]=a.getMonth();u[b+20>>2]=a.getFullYear()-1900;u[b+24>>2]=a.getDay();var c=a.getFullYear();u[b+28>>2]=(c%4!==0||c%100===0&&c%400!==
0?Ha:Ga)[a.getMonth()]+a.getDate()-1|0;u[b+36>>2]=-(a.getTimezoneOffset()*60);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();u[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;return 0},hb:(a,b)=>{A[a]&&(clearTimeout(A[a].id),delete A[a]);if(!b)return 0;var c=setTimeout(()=>{delete A[a];La(()=>lc(a,performance.now()))},b);A[a]={id:c,ae:b};return 0},nb:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();
e=(new Date(e,6,1)).getTimezoneOffset();v[a>>2]=Math.max(g,e)*60;u[b>>2]=Number(g!=e);b=f=>{var k=Math.abs(f);return`UTC${f>=0?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(B(a,c,17),B(b,d,17)):(B(a,d,17),B(b,c,17))},ib:function(a,b,c){if(!(a>=0&&a<=3))return 28;sa[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},ab:function(a,b,c){a=a?y(r,a):"";for(var d="",e=0;e<c;e++)d+=String.fromCharCode(r[b+e]);console.log(btoa(d));
b=document.createElement("a");b.setAttribute("href","data:application/octet-stream;base64,"+btoa(d));b.setAttribute("download",a);b.style.display="none";document.body.appendChild(b);b.click();document.body.removeChild(b)},A:function(a,b){a=a?y(r,a):"";b=b?y(r,b):"";var c=document.createElement("a");c.setAttribute("href","data:text/plain;charset=utf-8,"+encodeURIComponent(b));c.setAttribute("download",a);c.style.display="none";document.body.appendChild(c);c.click();document.body.removeChild(c)},hc:function(){h.emsc_js_onload=
cc},gc:function(){return navigator.userAgent.includes("Macintosh")?1:0},Za:function(){document.getElementById("picker").click()},Qa:function(a){if(window.localStorage===void 0)return 0;a=a?y(r,a):"";return(a=window.localStorage.getItem(a))?Sb(a):0},Ya:function(a){a=a?y(r,a):"";window.open(a)},Ta:function(a,b){a=a?y(r,a):"";b=b?y(r,b):"";window.localStorage.setItem(a,b)},Wa:()=>{ab();C=null},vb:()=>Date.now(),ma:()=>globalThis.devicePixelRatio??1,oa:(a,b,c)=>{a=H(a);if(!a)return-4;a=db(a);x[b>>3]=
a.width;x[c>>3]=a.height;return 0},Xa:()=>performance.now(),bb:(a,b)=>{function c(d){I(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},jb:a=>{var b=r.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);oa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},W:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),la:(a,b,c)=>{a=
H(a);if(!a)return-4;a.width=b;a.height=c;return 0},X:(a,b,c,d)=>jb(a,b,c,d,13,"focus"),V:(a,b,c,d)=>{if(!J.fullscreenEnabled())return-1;a=H(a);if(!a)return-4;kb(a,b,c,d,"webkitfullscreenchange");return kb(a,b,c,d,"fullscreenchange")},ea:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),ca:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),da:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),cb:(a,b,c)=>{a=I(a);$a(a,b,c)},ka:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),ha:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),ga:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),
ia:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),ja:(a,b,c,d)=>nb(a,b,c,d,6,"mouseup"),Z:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?ob(a,b,c,d):-4:-1,Y:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?pb(a,b,c,d):-4:-1,na:(a,b,c,d)=>qb(a,b,c,d),_:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),$:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),aa:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),ba:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),U:(a,b,c,d)=>{Hb(a,b,c,d,31,"webglcontextlost");return 0},T:(a,b,c,d)=>{Hb(a,b,c,d,32,
"webglcontextrestored");return 0},fa:(a,b,c,d)=>(a=H(a))?typeof a.onwheel!="undefined"?Ib(a,b,c,d):-1:-4,$a:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+5],powerPreference:Jb[u[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],desynchronized:!!p[b+33],kd:u[c+4],Qd:u[c+5],gd:p[b+24],xd:p[b+25],Td:u[c+7],Yd:p[b+32]};a=H(a);return!a||b.xd?0:Gb(a,b)},_a:a=>{U=Ab[a];h.ctx=M=U?.bd;return!a||M?0:-5},tb:(a,b)=>{var c=
0,d=0,e;for(e of Mb()){var g=b+c;v[a+d>>2]=g;c+=B(e,g,Infinity)+1;d+=4}return 0},ub:(a,b)=>{var c=Mb();v[a>>2]=c.length;a=0;for(var d of c)a+=Nb(d)+1;v[b>>2]=a;return 0},ra:()=>52,qb:()=>52,ob:function(){return 70},pb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=v[b>>2],k=v[b+4>>2];b+=8;for(var n=0;n<k;n++){var q=a,t=r[f+n],E=Ob[q];t&&t!==10?E.push(t):((q===1?ma:l)(y(E)),E.length=0)}e+=k}v[d>>2]=e;return 0},i:a=>M.activeTexture(a),E:(a,b)=>{M.attachShader(O[a],Q[b])},a:(a,b)=>{a==35051?M.dd=b:a==35052&&
(M.Jc=b);M.bindBuffer(a,N[b])},x:(a,b,c)=>{M.bindBufferBase(a,b,N[c])},Lb:(a,b,c,d,e)=>{M.bindBufferRange(a,b,N[c],d,e)},j:(a,b)=>{M.bindFramebuffer(a,xb[b])},Wb:(a,b)=>{M.bindRenderbuffer(a,yb[b])},h:(a,b)=>{M.bindSampler(a,R[b])},c:(a,b)=>{M.bindTexture(a,P[b])},S:a=>{M.bindVertexArray(zb[a])},N:(a,b,c,d)=>M.blendColor(a,b,c,d),O:(a,b)=>M.blendEquationSeparate(a,b),P:(a,b,c,d)=>M.blendFuncSeparate(a,b,c,d),yb:(a,b,c,d,e,g,f,k,n,q)=>M.blitFramebuffer(a,b,c,d,e,g,f,k,n,q),La:(a,b,c,d)=>{U.version>=
2?c&&b?M.bufferData(a,r,d,c,b):M.bufferData(a,b,d):M.bufferData(a,c?r.subarray(c,c+b):b,d)},H:(a,b,c,d)=>{var e=r;U.version>=2?c&&M.bufferSubData(a,b,e,d,c):M.bufferSubData(a,b,e.subarray(d,d+c))},Tb:a=>M.checkFramebufferStatus(a),Sb:(a,b,c,d)=>M.clearBufferfi(a,b,c,d),za:(a,b,c)=>{M.clearBufferfv(a,b,w,c>>2)},Rb:(a,b,c)=>{M.clearBufferiv(a,b,u,c>>2)},n:(a,b,c,d)=>{M.colorMask(!!a,!!b,!!c,!!d)},_b:a=>{M.compileShader(Q[a])},v:(a,b,c,d,e,g,f,k,n)=>{U.version>=2?M.Jc||!k?M.compressedTexSubImage2D(a,
b,c,d,e,g,f,k,n):M.compressedTexSubImage2D(a,b,c,d,e,g,f,r,n,k):M.compressedTexSubImage2D(a,b,c,d,e,g,f,r.subarray(n,n+k))},G:(a,b,c,d,e,g,f,k,n,q,t)=>{M.Jc?M.compressedTexSubImage3D(a,b,c,d,e,g,f,k,n,q,t):M.compressedTexSubImage3D(a,b,c,d,e,g,f,k,n,r,t,q)},ec:()=>{var a=Eb(O),b=M.createProgram();b.name=a;b.Nc=b.Lc=b.Mc=0;b.Zc=1;O[a]=b;return a},bc:a=>{var b=Eb(Q);Q[b]=M.createShader(a);return b},K:a=>M.cullFace(a),Oa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=N[d];e&&(M.deleteBuffer(e),e.name=
0,N[d]=null,d==M.dd&&(M.dd=0),d==M.Jc&&(M.Jc=0))}},w:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+c*4>>2],e=xb[d];e&&(M.deleteFramebuffer(e),e.name=0,xb[d]=null)}},q:a=>{if(a){var b=O[a];b?(M.deleteProgram(b),b.name=0,O[a]=null):S||=1281}},I:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=yb[d];e&&(M.deleteRenderbuffer(e),e.name=0,yb[d]=null)}},J:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=R[d];e&&(M.deleteSampler(e),e.name=0,R[d]=null)}},p:a=>{if(a){var b=Q[a];b?(M.deleteShader(b),Q[a]=null):S||=
1281}},k:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2],e=P[d];e&&(M.deleteTexture(e),e.name=0,P[d]=null)}},Na:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+c*4>>2];M.deleteVertexArray(zb[d]);zb[d]=null}},z:a=>M.depthFunc(a),y:a=>{M.depthMask(!!a)},d:a=>M.disable(a),Q:a=>{M.disableVertexAttribArray(a)},ta:(a,b,c)=>{M.drawArrays(a,b,c)},ua:(a,b,c,d)=>{M.drawArraysInstanced(a,b,c,d)},Aa:(a,b)=>{for(var c=Pb[a],d=0;d<a;d++)c[d]=u[b+d*4>>2];M.drawBuffers(c)},va:(a,b,c,d)=>{M.drawElements(a,b,c,d)},wa:(a,b,c,
d,e)=>{M.drawElementsInstanced(a,b,c,d,e)},g:a=>M.enable(a),Mb:a=>{M.enableVertexAttribArray(a)},l:(a,b,c,d)=>{M.framebufferRenderbuffer(a,b,c,yb[d])},e:(a,b,c,d,e)=>{M.framebufferTexture2D(a,b,c,P[d],e)},D:(a,b,c,d,e)=>{M.framebufferTextureLayer(a,b,P[c],d,e)},L:a=>M.frontFace(a),Ma:(a,b)=>{T(a,b,"createBuffer",N)},R:(a,b)=>{T(a,b,"createFramebuffer",xb)},Xb:(a,b)=>{T(a,b,"createRenderbuffer",yb)},Ga:(a,b)=>{T(a,b,"createSampler",R)},Ja:(a,b)=>{T(a,b,"createTexture",P)},Va:(a,b)=>{T(a,b,"createVertexArray",
zb)},Yb:(a,b)=>M.getAttribLocation(O[a],b?y(r,b):""),b:(a,b)=>Rb(a,b),dc:(a,b,c,d)=>{a=M.getProgramInfoLog(O[a]);a===null&&(a="(unknown error)");b=b>0&&d?B(a,d,b):0;c&&(u[c>>2]=b)},Da:(a,b,c)=>{if(c)if(a>=wb)S||=1281;else if(a=O[a],b==35716)a=M.getProgramInfoLog(a),a===null&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(b==35719){if(!a.Nc){var d=M.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Nc=Math.max(a.Nc,M.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.Nc}else if(b==35722){if(!a.Lc)for(d=
M.getProgramParameter(a,35721),b=0;b<d;++b)a.Lc=Math.max(a.Lc,M.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Lc}else if(b==35381){if(!a.Mc)for(d=M.getProgramParameter(a,35382),b=0;b<d;++b)a.Mc=Math.max(a.Mc,M.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Mc}else u[c>>2]=M.getProgramParameter(a,b);else S||=1281},Zb:(a,b,c,d)=>{a=M.getShaderInfoLog(Q[a]);a===null&&(a="(unknown error)");b=b>0&&d?B(a,d,b):0;c&&(u[c>>2]=b)},Ba:(a,b,c)=>{c?b==35716?(a=M.getShaderInfoLog(Q[a]),a===null&&(a="(unknown error)"),
u[c>>2]=a?a.length+1:0):b==35720?(a=M.getShaderSource(Q[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=M.getShaderParameter(Q[a],b):S||=1281},Ua:(a,b)=>{if(U.version<2)return S||=1282,0;var c=Bb[a];if(c)return b<0||b>=c.length?(S||=1281,0):c[b];switch(a){case 7939:return c=Qb().map(Sb),c=Bb[a]=c,b<0||b>=c.length?(S||=1281,0):c[b];default:return S||=1280,0}},Ca:(a,b)=>{b=b?y(r,b):"";if(a=O[a]){var c=a,d=c.Kc,e=c.ud,g;if(!d){c.Kc=d={};c.td={};var f=M.getProgramParameter(c,35718);for(g=0;g<f;++g){var k=M.getActiveUniform(c,
g);var n=k.name;k=k.size;var q=Tb(n);q=q>0?n.slice(0,q):n;var t=c.Zc;c.Zc+=k;e[q]=[k,t];for(n=0;n<k;++n)d[t]=n,c.td[t++]=q}}c=a.Kc;d=0;g=b;e=Tb(b);e>0&&(d=b.slice(e+1),d=parseInt(d)>>>0,g=b.slice(0,e));if((e=a.ud[g])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else S||=1281;return-1},xb:(a,b,c)=>{for(var d=Pb[b],e=0;e<b;e++)d[e]=u[c+e*4>>2];M.invalidateFramebuffer(a,d)},Ea:a=>{a=O[a];M.linkProgram(a);a.Kc=0;a.ud={}},o:(a,b)=>{a==3317?Cb=b:a==3314&&(Db=b);M.pixelStorei(a,b)},M:(a,
b)=>M.polygonOffset(a,b),Ab:a=>M.readBuffer(a),Vb:(a,b,c,d,e)=>M.renderbufferStorageMultisample(a,b,c,d,e),Fa:(a,b,c)=>{M.samplerParameterf(R[a],b,c)},f:(a,b,c)=>{M.samplerParameteri(R[a],b,c)},s:(a,b,c,d)=>M.scissor(a,b,c,d),$b:(a,b,c,d)=>{for(var e="",g=0;g<b;++g)e+=z(v[c+g*4>>2],d?v[d+g*4>>2]:void 0);M.shaderSource(Q[a],e)},Sa:(a,b,c)=>M.stencilFunc(a,b,c),ya:(a,b,c,d)=>M.stencilFuncSeparate(a,b,c,d),r:a=>M.stencilMask(a),Ra:(a,b,c)=>M.stencilOp(a,b,c),xa:(a,b,c,d)=>M.stencilOpSeparate(a,b,c,d),
Ia:(a,b,c,d,e)=>M.texStorage2D(a,b,c,d,e),Ha:(a,b,c,d,e,g)=>M.texStorage3D(a,b,c,d,e,g),u:(a,b,c,d,e,g,f,k,n)=>{if(U.version>=2){if(M.Jc){M.texSubImage2D(a,b,c,d,e,g,f,k,n);return}if(n){var q=Ub(k);M.texSubImage2D(a,b,c,d,e,g,f,k,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Ub(k);var t=g*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT*(Db||e)+Cb-1&-Cb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=
null;M.texSubImage2D(a,b,c,d,e,g,f,k,n)},F:(a,b,c,d,e,g,f,k,n,q,t)=>{if(M.Jc)M.texSubImage3D(a,b,c,d,e,g,f,k,n,q,t);else if(t){var E=Ub(q);M.texSubImage3D(a,b,c,d,e,g,f,k,n,q,E,t>>>31-Math.clz32(E.BYTES_PER_ELEMENT))}else M.texSubImage3D(a,b,c,d,e,g,f,k,n,q,null)},Kb:(a,b,c)=>{if(U.version>=2)b&&M.uniform1fv(V(a),w,c>>2,b);else{if(b<=288)for(var d=W[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+b*4>>2);M.uniform1fv(V(a),d)}},cc:(a,b)=>{M.uniform1i(V(a),b)},Fb:(a,b,c)=>{if(U.version>=2)b&&
M.uniform1iv(V(a),u,c>>2,b);else{if(b<=288)for(var d=Vb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+b*4>>2);M.uniform1iv(V(a),d)}},Jb:(a,b,c)=>{if(U.version>=2)b&&M.uniform2fv(V(a),w,c>>2,b*2);else{if(b<=144){b*=2;for(var d=W[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+b*8>>2);M.uniform2fv(V(a),d)}},Eb:(a,b,c)=>{if(U.version>=2)b&&M.uniform2iv(V(a),u,c>>2,b*2);else{if(b<=144){b*=2;for(var d=Vb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=
u.subarray(c>>2,c+b*8>>2);M.uniform2iv(V(a),d)}},Ib:(a,b,c)=>{if(U.version>=2)b&&M.uniform3fv(V(a),w,c>>2,b*3);else{if(b<=96){b*=3;for(var d=W[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+b*12>>2);M.uniform3fv(V(a),d)}},Db:(a,b,c)=>{if(U.version>=2)b&&M.uniform3iv(V(a),u,c>>2,b*3);else{if(b<=96){b*=3;for(var d=Vb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+b*12>>2);M.uniform3iv(V(a),
d)}},Hb:(a,b,c)=>{if(U.version>=2)b&&M.uniform4fv(V(a),w,c>>2,b*4);else{if(b<=72){var d=W[4*b],e=w;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=w.subarray(c>>2,c+b*16>>2);M.uniform4fv(V(a),d)}},Cb:(a,b,c)=>{if(U.version>=2)b&&M.uniform4iv(V(a),u,c>>2,b*4);else{if(b<=72){b*=4;for(var d=Vb[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+b*16>>2);M.uniform4iv(V(a),
d)}},Bb:(a,b,c,d)=>{if(U.version>=2)b&&M.uniformMatrix4fv(V(a),!!c,w,d>>2,b*16);else{if(b<=18){var e=W[16*b],g=w;d>>=2;b*=16;for(var f=0;f<b;f+=16){var k=d+f;e[f]=g[k];e[f+1]=g[k+1];e[f+2]=g[k+2];e[f+3]=g[k+3];e[f+4]=g[k+4];e[f+5]=g[k+5];e[f+6]=g[k+6];e[f+7]=g[k+7];e[f+8]=g[k+8];e[f+9]=g[k+9];e[f+10]=g[k+10];e[f+11]=g[k+11];e[f+12]=g[k+12];e[f+13]=g[k+13];e[f+14]=g[k+14];e[f+15]=g[k+15]}}else e=w.subarray(d>>2,d+b*64>>2);M.uniformMatrix4fv(V(a),!!c,e)}},m:a=>{a=O[a];M.useProgram(a);M.wd=a},Nb:(a,
b)=>{M.vertexAttribDivisor(a,b)},Ob:(a,b,c,d,e)=>{M.vertexAttribIPointer(a,b,c,d,e)},Pb:(a,b,c,d,e,g)=>{M.vertexAttribPointer(a,b,c,!!d,e,g)},t:(a,b,c,d)=>M.viewport(a,b,c,d),kb:Ja,Pa:function(){h.nd=a=>{ec()!=0&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.nd)},fc:function(){h.sd=a=>{var b=a.clipboardData.getData("text");$b(()=>{var c=X(b);dc(c)})};window.addEventListener("paste",h.sd)},Qb:function(){h.Zd=[];h.od=b=>{b.stopPropagation();b.preventDefault()};h.pd=
b=>{b.stopPropagation();b.preventDefault()};h.qd=b=>{b.stopPropagation();b.preventDefault()};h.rd=b=>{b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;h.$d=c;fc(c.length);for(let e=0;e<c.length;e++)$b(()=>{var g=X(c[e].name);hc(e,g)});var d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ic(b.clientX,b.clientY,d)};var a=h.Hc;a.addEventListener("dragenter",h.od,!1);a.addEventListener("dragleave",h.pd,!1);a.addEventListener("dragover",h.qd,!1);a.addEventListener("drop",
h.rd,!1)},fb:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},gb:function(a){h.Pc&&(URL.revokeObjectURL(h.Pc[a].Dd),h.Pc[a]=null)},zb:function(a,b){b!==0&&(document.title=z(Number(b)));a=z(Number(a));h.canvas!==void 0&&(typeof h.canvas==="object"?cb[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Hc=H(a);h.Hc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Hc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",
a)},Ka:function(){window.removeEventListener("beforeunload",h.nd)},ac:function(){window.removeEventListener("paste",h.sd)},Gb:function(){var a=h.Hc;a.removeEventListener("dragenter",h.od);a.removeEventListener("dragleave",h.pd);a.removeEventListener("dragover",h.qd);a.removeEventListener("drop",h.rd)},C:function(){h.Hc&&h.Hc.requestPointerLock&&h.Hc.requestPointerLock()},B:function(a,b,c){if(h.Hc){if(b===0)a="none";else if(c!=0)a=h.Pc[a].Fd;else switch(a){case 0:a="auto";break;case 1:a="default";
break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Hc.style.cursor=a}},eb:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(r.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ub:function(a){a=z(Number(a));var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},
db:function(){var a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){let c=b.value[0],d=b.value[1];$b(()=>{var e=X(c),g=X(d);kc(e,g)})}},pa:function(){return navigator.userAgent.includes("Macintosh")?1:0},qa:function(a,b){b=z(Number(b));switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
function nc(a=[]){var b=jc;a.unshift(ea);var c=a.length,d=Wb((c+1)*4),e=d,g;for(g of a)v[e>>2]=X(g),e+=4;v[e>>2]=0;try{var f=b(c,d);na=f;Ja(f)}catch(k){Ia(k)}}async function oc(){var a=da;ta();var b=h.setStatus;b&&(b("Running..."),await new Promise(c=>setTimeout(c,1)),setTimeout(b,1,""));m||(pc.jc(),h.onRuntimeInitialized?.(),h.noInitialRun||nc(a),va())}var pc;
(async function(){function a(d){d=pc=d.exports;h._util_emsc_loadfile=d.kc;L=d.lc;dc=h.__sapp_emsc_onpaste=d.mc;ec=h.__sapp_html5_get_ask_leave_site=d.nc;fc=h.__sapp_emsc_begin_drop=d.oc;hc=h.__sapp_emsc_drop=d.pc;ic=h.__sapp_emsc_end_drop=d.qc;h.__sapp_emsc_invoke_fetch_cb=d.rc;h.__sapp_emsc_set_fullscreen_flag=d.sc;jc=h._main=d.tc;kc=h.__sargs_add_kvp=d.uc;lc=d.wc;Yb=d.xc;Wb=d.yc;Xb=d.zc;pa=d.ic;fb=d.vc;oa();return pc}var b={a:mc},c=h.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});
ya??=h.locateFile?h.locateFile("vz80r.wasm",ia):ia+"vz80r.wasm";return function(d){return a(d.instance)}(await Ba(b))})().then(()=>oc());
